version: '3.5'

services:    
    database:
        image: melhor-db
        
        volumes:
            - db-volume:/var/lib/mysql

        network_mode: "host"
              
        ports:
            - "3306:3036"
        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: melhorenvio
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin

volumes:
    db-volume: