-- MySQL Script generated by MySQL Workbench
-- qui 15 jul 2021 10:06:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema melhorenvio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema melhorenvio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `melhorenvio` DEFAULT CHARACTER SET utf8 ;
USE `melhorenvio` ;

-- -----------------------------------------------------
-- Table `melhorenvio`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhorenvio`.`request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(8) NULL,
  `uri` VARCHAR(128) NULL,
  `size` INT NULL,
  `querystring` VARCHAR(128) NULL,
  `headers` JSON NULL,
  `url` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhorenvio`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhorenvio`.`route` (
  `id` VARCHAR(64) NOT NULL,
  `created_at` INT NULL,
  `hosts` VARCHAR(128) NULL,
  `methods` VARCHAR(128) NULL,
  `paths` VARCHAR(128) NULL,
  `protocols` VARCHAR(64) NULL,
  `preserve_host` TINYINT(1) NULL,
  `regex_priority` INT NULL,
  `strip_path` TINYINT(1) NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhorenvio`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhorenvio`.`response` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `size` INT NULL,
  `headers` JSON NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhorenvio`.`authenticated_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhorenvio`.`authenticated_entity` (
  `id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhorenvio`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhorenvio`.`service` (
  `id` VARCHAR(64) NOT NULL,
  `connect_timeout` INT NULL,
  `created_at` INT NULL,
  `host` VARCHAR(128) NULL,
  `name` VARCHAR(64) NULL,
  `path` VARCHAR(64) NULL,
  `port` INT NULL,
  `protocol` VARCHAR(16) NULL,
  `read_timeout` INT NULL,
  `retries` INT NULL,
  `updated_at` INT NULL,
  `write_timeout` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhorenvio`.`latencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhorenvio`.`latencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proxy` INT NULL,
  `kong` INT NULL,
  `request` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `melhorenvio`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melhorenvio`.`log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `upstream_uri` VARCHAR(128) NULL,
  `client_ip` VARCHAR(15) NULL,
  `started_at` INT NULL,
  `request_id` INT NULL,
  `route_id` VARCHAR(64) NULL,
  `response_id` INT NULL,
  `authenticated_entity_id` VARCHAR(64) NULL,
  `service_id` VARCHAR(64) NULL,
  `latencies_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_request1_idx` (`request_id` ASC),
  INDEX `fk_log_route1_idx` (`route_id` ASC),
  INDEX `fk_log_response1_idx` (`response_id` ASC),
  INDEX `fk_log_authenticated_entity1_idx` (`authenticated_entity_id` ASC),
  INDEX `fk_log_service1_idx` (`service_id` ASC),
  INDEX `fk_log_latencies1_idx` (`latencies_id` ASC),
  CONSTRAINT `fk_log_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `melhorenvio`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_route1`
    FOREIGN KEY (`route_id`)
    REFERENCES `melhorenvio`.`route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_response1`
    FOREIGN KEY (`response_id`)
    REFERENCES `melhorenvio`.`response` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_authenticated_entity1`
    FOREIGN KEY (`authenticated_entity_id`)
    REFERENCES `melhorenvio`.`authenticated_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `melhorenvio`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_latencies1`
    FOREIGN KEY (`latencies_id`)
    REFERENCES `melhorenvio`.`latencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;